### ISSUE TITLE
Want # of evictions by race, etc.

### ISSUE THREAD

**Issue by connie-ly** [mit-spatial-action/who-owns-mass-backend#7]
Not individual records, but rather by in aggregate scale (Maybe if the LLC has evicted >x tenants, add this demographical info into the website in consideration of small sample sizes and privacy)

Of the evicted, pie chart dividing tenants by race? 

In addition to race, other demographical info that would be interesting + considering intersectionality:
- Median household income
- Immigration status
- Sex
- Age
- Educational Attainment

Shows the reader which populations are the most evicted and discriminated against

Not sure if this type of information is obtainable from filings @ericrobskyhuntley

**Comment by ericrobskyhuntley** [comment]
Not possible without some methods I'm not willing to explore (e.g., inference of race from name, which some have used in larger-scale aggregated research into evictions, but I"m not willing to do it for any scale relevant to our application).
